# User config
author: "Diele Lobo"
tagline: "Diele's webpagee"
description: "My research..."
email: "lobo0010@umn.edu"
twitter: "https://twitter.com/dielelobo"
CV: "https://deelobo.github.io/cv/"

# Site config
baseurl: "/website"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
