# User config
author: "Diele"
tagline: "Diele's webpagee"
description: "..."
email: "pineapple@example.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "/website"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
